name: Java CI

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # POSTGRES_DB - name for the default database that is created
        postgresql db: library
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: test
        # POSTGRES_PASSWORD - superuser password
        postgresql password: 1234
    - name: Build with Maven
      run: mvn -B package --file pom.xml
